# Generated by Django 3.2.9 on 2021-12-01 02:21

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='create_date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(default=datetime.datetime(2021, 12, 1, 2, 21, 55, 630170, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
